[tool.poetry]
name = "referrers"
version = "0.1.0"
description = ""
authors = ["Neil Ferguson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3"
networkx = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
